### ISSUE TITLE
Missing template part for Orc.Controls.DropDownButton (ShouldCreateStyleForwarders=false)

### ISSUE THREAD

**Issue by lipchev** [WildGums/Orc.Theming#118]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x] .NET Core

## Component

Orc.Theming (4.0.2) / Orc.Controls.DropDownButton (4.0.8)

## Version of Library

Orchestra.Examples.MahApps (6.0.4)

## Version of OS(s) listed above with issue

Win 10, .net core 3.1

## Steps to Reproduce
1. Open the MahApps.Shell example from the Orchestra package 
2. Skip the call to `StyleHelper.CreateStyleForwardersForDefaultStyles()` by registering a NoForwardingThemingService (or simply commenting out [this line](https://github.com/WildGums/Orchestra/blob/5ddbda8684e6beeebc1e9510f4ade45eea677dec/src/Orchestra.Shell.Shared/Services/ApplicationInitializationServiceBase.cs#L44))

## Expected Behavior

(My guess):
The application should start with the implicit styles for all Orc.Controls (or there is a ResourceDictionary that can be imported for those)

## Actual Behavior
[ERROR] [Orc.Controls.DropDownButton] [1] Can't find template part 'PART_Arrow'
Exception thrown: 'System.InvalidOperationException' in Orc.Controls.dll

_I was able to fix the issue by manually setting the default style from_ `Orc.Styles.DropDownButton`

**Comment by GeertvanHorrik** [comment]
@ceo1647 what do you think?
