### ISSUE TITLE
ThemeSwitcher ignores any preset values (IBaseColorSchemeService, IAccentColorService)

### ISSUE THREAD

**Issue by lipchev** [WildGums/Orc.Theming#120]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x] .NET Core

## Component

Orc.Theming.Example

## Version of Library

Orc.Theming (4.0.2)

## Version of OS(s) listed above with issue

Win 10, .net core 3.1

## Steps to Reproduce
1. Change the AccentColorBrush defined in the [App.xaml](https://github.com/WildGums/Orc.Theming/blob/4b2e177cf39b138f929e80eaf7d1f64c3330f73c/src/Orc.Theming.Example/App.xaml#L7)
2. Run the example 

## Expected Behavior

The initial values provided by the injected services are taken assigned to their corresponding combo-boxes; the initial theme corresponds to the preset values.

## Actual Behavior

The values are reset during the construction of the [ThemeSwitcherViewModel ](https://github.com/WildGums/Orc.Theming/blob/4b2e177cf39b138f929e80eaf7d1f64c3330f73c/src/Orc.Theming/ViewModels/ThemeSwitcherViewModel.cs#L25)(using Orange & Light as defaults)

**Comment by GeertvanHorrik** [comment]
I thought I explicitly implemented this. Let me double check.

**Comment by GeertvanHorrik** [comment]
see https://github.com/WildGums/Orc.Theming/commit/5fedad779532bc3bce225a5856f90709db26edb1

Not sure how it got reverted. @ceo1647 , could you fix this in a hotfix?

**Comment by ceo1647** [comment]
ok... i'll look

**Comment by ceo1647** [comment]
should be fixed in a latest commit

**Comment by GeertvanHorrik** [comment]
Should be fixed, feel free to re-open if not.
