### ISSUE TITLE
It is not possible to set the default accent color and templates for some controls by call StyleHelper.CreateStyleForwardersForDefaultStyles(); in app.xaml

### ISSUE THREAD

**Issue by ghost** [WildGums/Orc.Theming#121]
- [ x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

orc.Theming

## Version of Library
4.0.2

## Version of OS(s) listed above with issue
win 10

## Steps to Reproduce
see a test repro attached.

## Expected Behavior
correct default accent color brush for all controls
correct margins and paddings in all controls.

## Actual Behavior

i'v tried to use the orc.Teming API as it has been done in Orc.Theming.Example. 
But still drop-down box and check box appear not to use the defined accent color brush. Only if i insert the ThemeSwitcherView in my MainWindow and set a color different than default, i'm was able to see the colors in controls.
The Capture text of Buttons without width definition doesn't have left and right padding. 
It is possible i'm mistaking something.
[ReproOrcThemin.zip](https://github.com/WildGums/Orc.Theming/files/5218303/ReproOrcThemin.zip)

**Comment by GeertvanHorrik** [comment]
@ceo1647 , please look into this.

**Comment by GeertvanHorrik** [comment]
Closing due to age
