### ISSUE TITLE
Improve ComboBox editable state

### ISSUE THREAD

**Issue by GeertvanHorrik** [WildGums/Orc.Theming#21]
1. It doesn't show focus / text indicator.
2. The padding seems a bit off from the non-editable combobox style

**Comment by Averus-a** [comment]
This is because of Style.Trigger of default Style
![image](https://user-images.githubusercontent.com/14249631/81490305-e8b04200-9291-11ea-9d6b-0c47d9dc8429.png)
Is there any way to override this besides defining a new global style (without x:Key)?

**Comment by GeertvanHorrik** [comment]
No that I am ware of

**Comment by Averus-a** [comment]
![image](https://user-images.githubusercontent.com/14249631/81733392-fdafef80-94a2-11ea-961e-90f826db9b5e.png)
The updated look of combobox. Fix padding, the text indicator is showing as well now.

**Comment by GeertvanHorrik** [comment]
Looks great!
